- name: Setting DNS zone transfer policies
  ansible.builtin.copy:
    content: "{{ djbdns_transfers }}"
    dest: /etc/axfrdns/tcp
    mode: "644"
  notify: Compile zone transfer rules into a hashed database

- name: Checking to see when the last xfer database was hashed
  ansible.builtin.stat:
    path: /etc/axfrdns/tcp.cdb
  register: xfer_db

- name: Checking to see when the last xfer config was modified
  ansible.builtin.stat:
    path: /etc/axfrdns/tcp
  register: xfer_conf

# If we want to support secondary nameservers, where the primary can SSH into
# the secondaries, we could modify /etc/tinydns/root/Makefile to push the
# data.cdb files to the remote servers as described in
# https://cr.yp.to/djbdns/run-server-bind.html
# Hobbiest typically get a friend to mirror their DNS and get updates via
# periodic zone transfers, and don't provide SSH access, so we haven't bothered
# to implement this feature.

- name: Deploying DNS zone file
  ansible.builtin.copy:
    content: "{{ djbdns_data }}"
    dest: /etc/tinydns/root/data
    mode: "644"
  notify: Compile zone file into a hashed database

- name: Checking to see when the last xfer database was hashed
  ansible.builtin.stat:
    path: /etc/tinydns/root/data.cdb
  register: data_db

- name: Checking to see when the last xfer config was modified
  ansible.builtin.stat:
    path: /etc/tinydns/root/data
  register: data_conf
