- name: Ensuring we have a directory for environment variables
  ansible.builtin.file:
    path: "{{ djbdns_tinydns_conf_dir }}/env"
    state: directory
    mode: "644"

- name: Setting ROOT environment variable
  ansible.builtin.copy:
    content: "{{ djbdns_tinydns_conf_dir }}/root"
    dest: "{{ djbdns_tinydns_conf_dir }}/env/ROOT"
    mode: "644"

- name: Setting IP environment variable
  ansible.builtin.copy:
    content: "{{ djbdns_bind_ip_address }}"
    dest: "{{ djbdns_tinydns_conf_dir }}/env/IP"
    mode: "644"

- name: Setting DNS zone transfer policies
  ansible.builtin.copy:
    content: "{{ djbdns_transfers }}"
    dest: "{{ djbdns_axfr_conf_dir }}/tcp"
    mode: "644"
  notify: Compile zone transfer rules into a hashed database

- name: Checking to see when the last xfer database was hashed
  ansible.builtin.stat:
    path: "{{ djbdns_axfr_conf_dir }}/tcp.cdb"
  register: xfer_db

- name: Checking to see when the last xfer config was modified
  ansible.builtin.stat:
    path: "{{ djbdns_axfr_conf_dir }}/tcp"
  register: xfer_conf

# If we want to support secondary nameservers, where the primary can SSH into
# the secondaries, we could modify /etc/tinydns/root/Makefile to push the
# data.cdb files to the remote servers as described in
# https://cr.yp.to/djbdns/run-server-bind.html
# Hobbiest typically get a friend to mirror their DNS and get updates via
# periodic zone transfers, and don't provide SSH access, so we haven't bothered
# to implement this feature.

- name: Deploying DNS zone file
  ansible.builtin.copy:
    content: "{{ djbdns_data }}"
    dest: "{{ djbdns_tinydns_conf_dir }}/root/zone-primary"
    mode: "644"
  notify: Compile zone file into a hashed database
  when: djbdns_data | length > 0

- name: Doing zone transfers
  ansible.builtin.command:
    chdir: "{{ djbdns_tinydns_conf_dir }}/root"
    cmd: tcpclient {{ item.host }} {{ item.port | default('53') }} axfr-get {{ item.zone }} zone-{{ item.filename }} zone-{{ item.filename }}.tmp
  notify: Compile zone file into a hashed database
  loop: "{{ djbdns_zone_xfers }}"

- name: Combining zone transfers (if any) with zone file (if any)
  ansible.builtin.shell:
    chdir: "{{ djbdns_tinydns_conf_dir }}/root"
    cmd: sort -u zone-* > data
  when: djbdns_data | length > 0 or djbdns_zone_xfers | length > 0

- name: Checking to see when the last xfer database was hashed
  ansible.builtin.stat:
    path: "{{ djbdns_tinydns_conf_dir }}/root/data.cdb"
  register: data_db

- name: Checking to see when the last xfer config was modified
  ansible.builtin.stat:
    path: "{{ djbdns_tinydns_conf_dir }}/root/data"
  register: data_conf

# The above two variables are used in the handler, which will recompile the zone
# file if needed.
