- name: Install dependencies to run the service
  ansible.builtin.package:
    name:
      - daemontools
      - daemontools-run
      - ucspi-tcp
  when: djbdns_source_install

- name: Installing djbdns from your distro's repos
  ansible.builtin.package:
    name:
      - tinydns
      - axfrdns
      - ucspi-tcp
  when: not djbdns_source_install
