- name: Ensuring we have all the dependencies required to run the service
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/dependencies.yml"

- name: Checking to see if djbdns is already installed
  ansible.builtin.shell:
    cmd: which tinydns
  changed_when: false
  failed_when: false
  register: executable

- name: Compiling and installing djbdns (if necessary)
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  when: executable.stdout | length == 0

- name: Configuring djbdns
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/configure.yml"

- name: Starting the services
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/start.yml"

# To see that the service is running, log onto the server and run
# `svstat /etc/service/tinydns` (if using daemontools) or
# `sv status /etc/service/tinydns` (if using runit).
