- name: Compile zone transfer rules into a hashed database
  when: not xfer_db.stat.exists or xfer_conf.stat.mtime > xfer_db.stat.mtime
  ansible.builtin.command:
    cmd: make
    chdir: /etc/axfrdns
  register: xfer_rebuid
  changed_when: not xfer_rebuild.stdout | search("is up to date.")

- name: Compile zone file into a hashed database
  when: not data_db.stat.exists or data_conf.stat.mtime > data_db.stat.mtime
  ansible.builtin.command:
    cmd: make
    chdir: /etc/tinydns/root
  register: data_rebuid
  changed_when: not data_rebuild.stdout | search("is up to date.")
